don't depend on local blueprint for now
This was giving strange errors on github actions

```
Error: Command failed with exit code 1: npm install git+file:///home/runner/work/standard-node-template/standard-node-template#semver:1.0.0
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for undefined
```

https://github.com/kellyselden/standard-node-template/pull/95/checks?check_run_id=2447652254

Couldn't repro locally.